interface Album {
  idAlbum: string;
  idArtist: string;
  idLabel: string;
  intLoved: string;
  intSales: string;
  intScore: string;
  intScoreVotes: string;
  intYearReleased: string;
  strAlbum: string;
  strAlbum3DCase: string;
  strAlbum3DFace: string;
  strAlbum3DFlat: string;
  strAlbum3DThumb: string;
  strAlbumCDart: string;
  strAlbumSpine: string;
  strAlbumStripped: string;
  strAlbumThumb: string;
  strAlbumThumbBack: string;
  strAlbumThumbHQ: string | null;
  strAllMusicID: string;
  strAmazonID: string | null;
  strArtist: string;
  strArtistStripped: string;
  strBBCReviewID: string;
  strDescriptionCN: string | null;
  strDescriptionDE: string | null;
  strDescriptionEN: string;
  strDescriptionES: string;
  strDescriptionFR: string;
  strDescriptionHU: string | null;
  strDescriptionIL: string | null;
  strDescriptionIT: string | null;
  strDescriptionJP: string | null;
  strDescriptionNL: string | null;
  strDescriptionNO: string | null;
  strDescriptionPL: string | null;
  strDescriptionPT: string;
  strDescriptionRU: string | null;
  strDescriptionSE: string | null;
  strDiscogsID: string;
  strGeniusID: string | null;
  strGenre: string;
  strItunesID: string | null;
  strLabel: string;
  strLocation: string | null;
  strLocked: string;
  strLyricWikiID: string | null;
  strMood: string;
  strMusicBrainzArtistID: string;
  strMusicBrainzID: string;
  strMusicMozID: string;
  strRateYourMusicID: string;
  strReleaseFormat: string;
  strReview: string;
  strSpeed: string;
  strStyle: string;
  strTheme: string | null;
  strWikidataID: string;
  strWikipediaID: string;
}

export default Album;
